services:
  - type: web
    name: contacts-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.main:app --host 0.0.0.0 --port 8000
    runtime: python
    pythonVersion: 3.11.9
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
